#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE $FEDORA_DB_USER LOGIN PASSWORD '$FEDORA_DB_PASSWORD';
  CREATE DATABASE fcrepo WITH ENCODING='UTF8';
  GRANT ALL PRIVILEGES ON DATABASE fcrepo TO $FEDORA_DB_USER;
EOSQL
