version: '2'

services:
  db:
    image: avalonmediasystem/db:fedora4
    build: ./db
    volumes:
      - ./data/database:/data
    environment:
      - AVALON_DB_PASSWORD=${AVALON_DB_PASSWORD}
      - AVALON_DB_USER=${AVALON_DB_USER}      
      - FEDORA_DB_PASSWORD=${FEDORA_DB_PASSWORD}
      - FEDORA_DB_USER=${FEDORA_DB_USER}      
      - PGDATA=/data
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
       - "5432:5432"        
  fedora:
    image: avalonmediasystem/fedora:4.7.5
    build:
      context: ./fedora
      args:
        - FEDORA_VERSION=4.7.5
    environment:
      - FEDORA_DB_PASSWORD=${FEDORA_DB_PASSWORD}
      - JAVA_OPTIONS=-Dfcrepo.postgresql.password=${FEDORA_DB_PASSWORD} -Dfcrepo.postgresql.username=fedora -Dfcrepo.postgresql.host=db -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json -Dfcrepo.home=/data
    depends_on:
      - db
    volumes:
      - ./data/fedora:/data
    ports:
       - "8080:8080"      
  solr:
    image: avalonmediasystem/solr:latest
    build:
      context: ./solr
      args:
        - AVALON_BRANCH
        - AVALON_REPO
        - AVALON_REPO_RAW
    volumes:
      - ./data/solr:/opt/solr/server/solr/mycores      
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    ports:
       - "8983:8983"      
  hls:
    hostname: localhost:8880
    image: 10.55.134.48/avalon/nginx:${RANCHER_IMAGE_VERSION}
    build:
      context: ./nginx
    volumes:
      - ./data/masterfiles:/mnt/avalon/masterfiles  
    environment:
      - env_rtmp_avalon_url=${RTMP_AVALON_URL}
      - env_avalon_streaming_port=8880
      - env_master_file_location=/mnt/avalon/masterfiles
      - env_proxy_pass_ip=avalon
    ports:
       - "8880:8880"
  redis:
    container_name: ${REDIS_CONTAINER_NAME} 
    image: redis:alpine
  avalon: &avalon
    container_name: ${AVALON_CONTAINER_NAME} 
    image: ${VIC_SERVER}/avalon/${AVALON_CONTAINER_NAME}:${RANCHER_IMAGE_VERSION}
    build:
      context: ./avalon
      args:
        - AVALON_BRANCH
        - AVALON_REPO        
        - RAILS_ENV
        - SECRET_KEY_BASE   
        - CLIENT_MAX_BODY_SIZE=${CLIENT_MAX_BODY_SIZE}  
        - SOLR_HOST_YML=${SOLR_HOST}  
        - SOLR_PORT_YML=${SOLR_PORT}  
        - SOLR_BASE_PATH_YML=${SOLR_BASE_PATH}       
        - FEDORA_HOST_YML=${FEDORA_HOST}  
        - FEDORA_PORT_YML=${FEDORA_PORT}  
        - FEDORA_BASE_PATH_YML=${FEDORA_NAMESPACE}  
        - FEDORA_USER_YML=${FEDORA_USER}  
        - FEDORA_PASSWORD_YML=${FEDORA_PASSWORD}       
    depends_on:
      - db
      - fedora
      - solr
      - redis
    environment:
      - APP_NAME
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - ASSET_HOST
      - DATABASE_URL=${DATABASE_URL}
      - ENCODE_WORK_DIR=/mnt/avalon/masterfiles
      - FEDORA_BASE_PATH
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=${FEDORA_URL}
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY=delete
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=${RAILS_ENV}
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=${SOLR_URL}
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
      - env_ldap_password=${LDAP_PASSWORD}  
      - env_ldap_user=${LDAP_USER}  
      - env_redis_host=${REDIS_HOST}   
      - env_redis_port=6379        
      - env_avalon_hostname=localhost  
      - env_avalon_port=3000
      - env_avalon_protocol=http
      - env_dropbox_path=/mnt/avalon/dropbox
      - env_dropbox_upload_uri=\\cifs.library.tamu.edu/avalon/dropbox/
      - env_encoding_working_file_path=/mnt/avalon/ingest  
      - env_email_comments=dhahn@library.tamu.edu
      - env_email_notification=dhahn@library.tamu.edu
      - env_email_support=dhahn@library.tamu.edu
      - env_timeliner_url=http://localhost:3000/timeliner      
      - env_streaming_http_base=http://localhost:8880/avalon
      - env_streaming_rtmp_base=rtmp://localhost:8880/avalon
      - env_streaming_content_path=/mnt/avalon/masterfiles    
    volumes:
      - ./data/masterfiles:/mnt/avalon/masterfiles
      - ./data/dropbox:/mnt/avalon/dropbox   
      - ./data/dropbox:/mnt/avalon/ingest         
      - ./data/gems:/gems
    ports:
      - "3000:80"
  worker:
    <<: *avalon
    container_name: ${AVALON_CONTAINER_NAME}_worker 
    command: su -m -c "cd /home/app/avalon && RAILS_ENV=${RAILS_ENV} bundle exec sidekiq -C config/sidekiq.yml" app
    environment:
      - env_redis_host=${REDIS_HOST}   
      - env_redis_port=6379        
      - env_encoding_working_file_path=/mnt/avalon/ingest  
      - env_timeliner_url=http://localhost:3000/timeliner      
      - env_streaming_http_base=http://localhost:8880/avalon
      - env_streaming_rtmp_base=rtmp://localhost:8880/avalon
      - env_streaming_content_path=/mnt/avalon/masterfiles     
    volumes:
      - ./data/masterfiles:/mnt/avalon/masterfiles
      - ./data/dropbox:/mnt/avalon/dropbox   
      - ./data/dropbox:/mnt/avalon/ingest         
    ports: []
