version: '2'

volumes:
  streaming:
  database:
  fedora:
  solr:

networks:
  internal:
  external:
  
services:
  db:
    container_name: ${DB_CONTAINER_NAME}  
    image: avalonmediasystem/db:fedora4
    build: ./db
    volumes:
      - database:/data
    environment:
      - AVALON_DB_PASSWORD
      - FEDORA_DB_PASSWORD
      - PGDATA=/data
      - POSTGRES_USER=${POSTGRES_USER}
  fedora:
    container_name: ${FEDORA_CONTAINER_NAME}  
    image: avalonmediasystem/fedora:4.7.5
    build:
      context: ./fedora
      args:
        - FEDORA_VERSION=4.7.5
    environment:
      - FEDORA_DB_PASSWORD
      - JAVA_OPTIONS=-Dfcrepo.postgresql.password=${FEDORA_DB_PASSWORD} -Dfcrepo.postgresql.username=fedora -Dfcrepo.postgresql.host=db -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json -Dfcrepo.home=/data
    depends_on:
      - db
    volumes:
      - fedora:/data
    ports:
       - "8080:8080"
  solr:
    container_name: ${SOLR_CONTAINER_NAME}
    image: avalonmediasystem/solr:latest
    build:
      context: ./solr
      args:
        - AVALON_REPO_RAW
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
  hls:
    hostname: kaltura-dev
    domainname: library.tamu.edu
    image: 10.55.134.48/avalon/nginx:${RANCHER_IMAGE_VERSION}
    build:
      context: ./nginx
    environment:
      - env_avalon_streaming_port
      - env_master_file_location
      - env_proxy_pass_ip
      - env_rtmp_avalon_url    
    ports:
       - "8880:80"
       - "9080:80"
  redis:
    container_name: ${REDIS_CONTAINER_NAME} 
    image: redis:alpine
  avalon: &avalon
    container_name: ${AVALON_CONTAINER_NAME} 
    image: ${VIC_SERVER}/avalon/${AVALON_CONTAINER_NAME}:${RANCHER_IMAGE_VERSION}
    build:
      context: ./avalon
      args:
        AVALON_BRANCH: ${AVALON_BRANCH}  
        AVALON_REPO: ${AVALON_REPO}  
        AVALON_REPO_RAW: ${AVALON_REPO_RAW}  
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}  
        BASE_URL: ${BASE_URL}
        RAILS_ENV: ${RAILS_ENV}  
        EMAIL_NOTIFICATION: ${EMAIL_NOTIFICATION}   
        APP_NAME: ${APP_NAME}   
        EMAIL_SUPPORT: ${EMAIL_SUPPORT}   
        EMAIL_COMMENTS: ${EMAIL_COMMENTS}   
        SOLR_URL: ${SOLR_URL}   
        DATABASE_URL: ${DATABASE_URL}          
        FEDORA_URL: ${FEDORA_URL}   
        REDIS_HOST: ${REDIS_HOST}    
        STREAMING_HOST: ${STREAMING_HOST}          
    depends_on:
      - db
      - fedora
      - solr
      - redis
    environment:
      - APP_NAME=${APP_NAME}  
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}  
      - ASSET_HOST
      - SETTINGS__DOMAIN
      - SETTINGS__DROPBOX__PATH=/masterfiles/dropbox
      - SETTINGS__DROPBOX__UPLOAD_URI=./masterfiles/dropbox
      - SETTINGS__ENCODING__WORKING_FILE_PATH=/masterfiles
      - SETTINGS__EMAIL__COMMENTS=${EMAIL_COMMENTS}  
      - SETTINGS__EMAIL__NOTIFICATION=${EMAIL_NOTIFICATION}  
      - SETTINGS__EMAIL__SUPPORT=${EMAIL_SUPPORT}    
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__STREAMING__HTTP_BASE=http://${STREAMING_HOST}:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SETTINGS__REDIS__HOST=${REDIS_HOST}
      - SETTINGS__REDIS__PORT=6379
      - DATABASE_URL=${DATABASE_URL}
      - ENCODE_WORK_DIR=/streamfiles
      - FEDORA_BASE_PATH
      - FEDORA_NAMESPACE
      - FEDORA_URL=${FEDORA_URL}
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY=delete
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=${RAILS_ENV}
      - SMTP_ADDRESS=
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=${SOLR_URL}
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
      - env_ldap_password
      - env_ldap_user
      - env_redis_host=${REDIS_HOST}     
    volumes:
      - ./masterfiles:/masterfiles
      - ./gems:/gems
      - streaming:/streamfiles
    ports:
      - "3000:80"
  worker:
    <<: *avalon
    container_name: ${AVALON_CONTAINER_NAME}_worker 
    command: su -m -c "cd /home/app/avalon && RAILS_ENV=${RAILS_ENV} bundle exec sidekiq -C config/sidekiq.yml" app
    environment:
      - RAILS_ENV=${RAILS_ENV}     
    ports: []
