version: '3'

volumes:
  db-fedora:
  db-avalon:
  masterfiles:
  streaming:
  fedora:
  work:
  solr:
  gems:

networks:
  external:
  internal:

services:
  db-fedora:
    image: postgres
    volumes:
      - db-fedora:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fcrepo
      - POSTGRES_PASSWORD=known-happen-machine-DARE
    networks:
      internal:
  db-avalon:
    image: postgres
    volumes:
      - db-avalon:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_DB=avalon
      - POSTGRES_PASSWORD=orderly-ocean-tube-stick
    networks:
      internal:
  fedora:
    image: avalonmediasystem/fedora:4.7.5
    depends_on:
      - db-fedora
    volumes:
      - fedora:/var/lib/jetty/data
    environment:
      - JAVA_OPTIONS=-Dfcrepo.home=/var/lib/jetty/data -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json -Dfcrepo.postgresql.username=postgres -Dfcrepo.postgresql.password=known-happen-machine-DARE -Dfcrepo.postgresql.host=db-fedora
    networks:
      internal:
  solr:
    # image: solr:6.6-alpine 
    image: solr:7.0-alpine 
    volumes:
      - solr:/opt/solr/server/solr/mycores
    command: bin/solr -cloud -noprompt -f -p 8983
    networks:
      internal:
  matterhorn:
    image: avalonmediasystem/matterhorn
    volumes:
      - masterfiles:/masterfiles
      - streaming:/streamfiles
      - work:/work
    ports:
      - "8080:8080"
    networks:
      internal:
  hls:
    image: avalonmediasystem/nginx
    volumes:
      - streaming:/data
    ports:
       - "8880:80"
    networks:
      internal:
  redis:
    image: redis:alpine
    networks:
      internal:
  avalon:
    image: avalonmediasystem/avalon:6.4.4-ee
    build:
      context: ./avalon
    depends_on:
      - db-avalon
      - fedora
      - solr
      - redis
    environment:
      - APP_NAME=archivo
      - SECRET_KEY_BASE=3fe397575565365108556c3e5549f139e8078a8ec8fd2675a83de96289b30550a266ac04488d7086322efbe573738e7b3ae005b2e3d9afd718aa337fa5e329cf
      - SETTINGS__DOMAIN__HOST=archivo.dlib.indiana.edu
      - DATABASE_URL=postgres://postgres:orderly-ocean-tube-stick@db-avalon/avalon
      - SETTINGS__DROPBOX__PATH=/masterfiles/dropbox
      - SETTINGS__DROPBOX__UPLOAD_URI=./masterfiles/dropbox
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - SETTINGS__FFMPEG_PATH=/usr/bin/ffmpeg
      - MASTER_FILE_STRATEGY=delete
      - MATTERHORN_URL=http://matterhorn_system_account:CHANGE_ME@matterhorn:8080/
      - SETTINGS__MATTERHORN__MEDIA_PATH=/masterfiles
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=production
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SOLR_URL=http://solr:8983/solr/avalon
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__STREAMING__HTTP_BASE=http://archivo.dlib.indiana.edu:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SYSTEM_GROUPS=administrator,group_manager,manager
    volumes:
      - masterfiles:/masterfiles
      - gems:/gems
    ports:
      - "80:80"
    networks:
      internal:
