version: '3'

volumes:
  gems:
  streaming:
  database:
  fedora:
  work:
  solr:

networks:
  external:
  internal:
    
services:
  db:
    image: avalonmediasystem/db:fedora4
    build: ./db
    volumes:
      - database:/data
    environment:
      - AVALON_DB_PASSWORD
      - FEDORA_DB_PASSWORD
      - PGDATA=/data
      - POSTGRES_USER=postgres
    networks:
      internal:
  fedora:
    image: avalonmediasystem/fedora:4.7.4
    build: 
      context: ./fedora
      args:
        - FEDORA_DB_PASSWORD
        - FEDORA_VERSION=4.7.4
    environment:
      - JAVA_OPTIONS=${JAVA_OPTIONS} -Dfcrepo.postgresql.password=${FEDORA_DB_PASSWORD} -Dfcrepo.postgresql.username=fedora -Dfcrepo.postgresql.host=db -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json
    depends_on:
      - db
    volumes:
      - fedora:/data
    networks:
      internal:
  solr:
    image: avalonmediasystem/solr:latest
    build: 
      context: ./solr
      args:
        - AVALON_BRANCH
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    networks:
      internal:
  matterhorn:
    image: avalonmediasystem/matterhorn
    build: 
      context: ./matterhorn
      args:
        - MATTERHORN_VER=1.4
        - MATTERHORN_BRANCH=1.4.x
    volumes:
      - ./masterfiles:/masterfiles
      - streaming:/streamfiles
      - work:/work
    networks:
      internal:
  hls:
    image: avalonmediasystem/nginx
    build:
      context: ./nginx
    volumes:
      - streaming:/data
    ports:
       - "8880:80"
    networks:
      external:
  redis:
    image: redis:alpine
    networks:
      internal:
  avalon:
    image: avalonmediasystem/avalon:7.0
    build: 
      context: ./avalon
      args:
        - AVALON_BRANCH=pg
        - SECRET_KEY_BASE=3fe397575565365108556c3e5549f139e8078a8ec8fd2675a83de96289b30550a266ac04488d7086322efbe573738e7b3ae005b2e3d9afd718aa337fa5e329cf
        - SETTINGS__DOMAIN=https://localhost/
    depends_on:
      - db
      - fedora
      - solr
      - redis
    environment:
      - APP_NAME
      - ASSET_HOST
      - DATABASE_URL=postgres://avalon:${AVALON_DB_PASSWORD}@db/avalon
      - SETTINGS__DROPBOX__PATH=/masterfiles/dropbox
      - SETTINGS__DROPBOX__UPLOAD_URI=./masterfiles/dropbox
      - SECRET_KEY_BASE=3fe397575565365108556c3e5549f139e8078a8ec8fd2675a83de96289b30550a266ac04488d7086322efbe573738e7b3ae005b2e3d9afd718aa337fa5e329cf
      - EMAIL_COMMENTS
      - EMAIL_NOTIFICATION
      - EMAIL_SUPPORT
      - FEDORA_BASE_PATH
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY=delete
      - MATTERHORN_URL=http://matterhorn_system_account:CHANGE_ME@matterhorn:8080/
      - SETTINGS__MATTERHORN__MEDIA_PATH=/masterfiles
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=production
      - REDIS_SERVER=redis:6379
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=http://solr:8983/solr/avalon
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__STREAMING__HTTP_BASE=http://${STREAMING_HOST}:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
    volumes:
      - ./masterfiles:/masterfiles
      - gems:/gems
      - ./avalon/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      external:
      internal:
