version: '3'
    
services:
  avalon:
    image: avalonmediasystem/avalon:7.0-dev
    build: 
      context: ./avalon
      dockerfile: Dockerfile-dev
      args:
        - AVALON_BRANCH=pg
        - SECRET_KEY_BASE=3fe397575565365108556c3e5549f139e8078a8ec8fd2675a83de96289b30550a266ac04488d7086322efbe573738e7b3ae005b2e3d9afd718aa337fa5e329cf
        - SETTINGS__DOMAIN=http://localhost/
    volumes:
      - ./masterfiles:/masterfiles
      - gems:/home/app/avalon/gems
      - ../avalon-bundle:/home/app/avalon 
